name: deploy-pypi

on:
    push:
        branches:
            - main
    release:
        types:
            - published

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        name: Publish python distribution to PyPi
        steps:
            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install twine and wheel
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install --upgrade twine
                  python -m pip install --upgrade wheel

            - name: Checkout
              uses: actions/checkout@master

            - name: Build distribution
              run: |
                  python setup.py sdist
                  python setup.py bdist_wheel
                  twine check dist/*

            - name: Publish to PyPi
              uses: pypa/gh-action-pypi-publish@master
              with:
                  user: __token__
                  password: ${{ secrets.pypi_password }}
