name: deploy-docs

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'

            # Build sphinx in /docs/build
            - name: Build Sphinx
              run: |
                  sudo apt-get update
                  sudo apt-get install graphviz -y
                  python -m pip install --upgrade pip
                  python -m pip install .[docs]
                  export PATH=$HOME/.local/bin:$PATH
                  make html --directory=docs
                  touch docs/build/html/.nojekyll
                  echo 'Visit [Documentation](https://ameli.github.io/ortho/index.html).' > docs/build/html/README.md

            # Deploy to github pages
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: docs/build/html
                branch: gh-pages
